#!/bin/sh
 
export GALLEON_MAVEN_ARGS="-Dcom.redhat.xpaas.repo.jbossorg"
export MAVEN_ARGS_APPEND="${MAVEN_ARGS_APPEND} -Dcom.redhat.xpaas.repo.jbossorg"
. "${JBOSS_CONTAINER_WILDFLY_S2I_MODULE}/assemble.sh"
