#!/bin/sh

echo ""
echo "********************************************************************************************"
echo "  WARNING: Starting WildFly 26.0.0.Final, the quay.io/wildfly/wildfly-centos7 and "
echo "  quay.io/wildfly/wildfly-runtime-centos7 images are being deprecated and will be replaced "
echo " by new images in a future release."
echo "********************************************************************************************"
echo ""

export CONFIG_ADJUSTMENT_MODE=cli
export MAVEN_ARGS_APPEND="${MAVEN_ARGS_APPEND} -Dcom.redhat.xpaas.repo.jbossorg"
. "${JBOSS_CONTAINER_WILDFLY_S2I_MODULE}/assemble.sh"
